package io.github.wphillipmoore.mq.rest.admin.mapping;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;

class MappingExceptionTest {

  private static final MappingIssue SAMPLE_ISSUE =
      new MappingIssue(
          MappingDirection.REQUEST, MappingReason.UNKNOWN_KEY, "badAttr", null, null, "queue");

  @Test
  void constructionWithAutoGeneratedMessage() {
    MappingException ex = new MappingException(List.of(SAMPLE_ISSUE));

    assertThat(ex.getMessage()).startsWith("Mapping failed with 1 issue(s):");
    assertThat(ex.getMessage()).contains("direction=REQUEST");
    assertThat(ex.getMessage()).contains("reason=UNKNOWN_KEY");
    assertThat(ex.getMessage()).contains("attribute=badAttr");
    assertThat(ex.getMessage()).contains("qualifier=queue");
  }

  @Test
  void constructionWithExplicitMessage() {
    MappingException ex = new MappingException("custom message", List.of(SAMPLE_ISSUE));

    assertThat(ex.getMessage()).isEqualTo("custom message");
  }

  @Test
  void getIssuesReturnsCorrectIssues() {
    MappingException ex = new MappingException(List.of(SAMPLE_ISSUE));

    assertThat(ex.getIssues()).containsExactly(SAMPLE_ISSUE);
  }

  @Test
  void issuesListIsUnmodifiable() {
    List<MappingIssue> mutableList = new ArrayList<>();
    mutableList.add(SAMPLE_ISSUE);
    MappingException ex = new MappingException(mutableList);

    assertThatThrownBy(() -> ex.getIssues().add(SAMPLE_ISSUE))
        .isInstanceOf(UnsupportedOperationException.class);
  }

  @Test
  void nullIssuesThrowsNullPointerException() {
    assertThatThrownBy(() -> new MappingException(null))
        .isInstanceOf(NullPointerException.class)
        .hasMessage("issues");
  }

  @Test
  void emptyIssuesThrowsIllegalArgumentException() {
    assertThatThrownBy(() -> new MappingException(List.of()))
        .isInstanceOf(IllegalArgumentException.class)
        .hasMessage("issues must not be empty");
  }

  @Test
  void multipleIssuesMessageContainsAllDetails() {
    MappingIssue first =
        new MappingIssue(
            MappingDirection.REQUEST, MappingReason.UNKNOWN_KEY, "badAttr", null, null, "queue");
    MappingIssue second =
        new MappingIssue(
            MappingDirection.RESPONSE, MappingReason.UNKNOWN_VALUE, "status", "XYZ", 0, "queue");

    MappingException ex = new MappingException(List.of(first, second));

    assertThat(ex.getMessage()).startsWith("Mapping failed with 2 issue(s):");
    assertThat(ex.getMessage()).contains("attribute=badAttr");
    assertThat(ex.getMessage()).contains("attribute=status");
    assertThat(ex.getMessage()).contains("value=XYZ");
    assertThat(ex.getMessage()).contains("index=0");
  }

  @Test
  void isRuntimeExceptionNotMqRestException() {
    MappingException ex = new MappingException(List.of(SAMPLE_ISSUE));

    assertThat(ex).isInstanceOf(RuntimeException.class);
    assertThat(ex)
        .isNotInstanceOf(io.github.wphillipmoore.mq.rest.admin.exception.MqRestException.class);
  }

  @Test
  void nullIssuesWithExplicitMessageThrowsNullPointerException() {
    assertThatThrownBy(() -> new MappingException("msg", null))
        .isInstanceOf(NullPointerException.class)
        .hasMessage("issues");
  }

  @Test
  void emptyIssuesWithExplicitMessageThrowsIllegalArgumentException() {
    assertThatThrownBy(() -> new MappingException("msg", List.of()))
        .isInstanceOf(IllegalArgumentException.class)
        .hasMessage("issues must not be empty");
  }

  @Test
  void autoMessageShowsDashForNullOptionalFields() {
    MappingIssue issue =
        new MappingIssue(
            MappingDirection.REQUEST, MappingReason.UNKNOWN_KEY, "attr", null, null, null);
    MappingException ex = new MappingException(List.of(issue));

    assertThat(ex.getMessage()).contains("index=-");
    assertThat(ex.getMessage()).contains("qualifier=-");
    assertThat(ex.getMessage()).contains("value=-");
  }
}
