[project]
repository-type = "library"
versioning-scheme = "library"
branching-model = "library-release"
release-model = "artifact-publishing"
primary-language = "java"

[ci]
versions = ["17", "21"]
integration-tests = true

[markdownlint]
ignore = ["docs/site/docs/mappings"]

[publish]
release = true
docs = true

[dependencies]
vergil = "v2.0"
